{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Excercises"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "237.538333333\n"
     ]
    }
   ],
   "source": [
    "# (1) Compute the average of a list of numbers. Use sum() and len()\n",
    "L=[23,32,121,22,1222.23,5]\n",
    "avg = sum(L)/len(L)\n",
    "print(avg)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# (2) Compute the number of times each word occurs in the following text.\n",
    "# Transform all words to lower case. Output a list of\n",
    "#  word,count pairs, one pair per line sorted from highest to lowest count."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " bands which have connected them with another  and to assume among the powers of the earth  the separate and equal station to which the Laws of Nature and of Nature's God entitle them  a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation   We hold these truths to be self evident  that all men are created equal  that they are endowed by their Creator with certain unalienable Rights  that among these are Life  Liberty and the pursuit of Happiness   That to secure these rights  Governments are instituted among Men  deriving their just powers from the consent of the governed    That whenever any Form of Government becomes destructive of these ends  it is the Right of the People to alter or to abolish it  and to institute new Government  laying its foundation on such principles and organizing its powers in such form  as to them shall seem most likely to effect their Safety and Happiness  Prudence  indeed  will dictate that Governments long established should not be changed for light and transient causes  and accordingly all experience hath shewn  that mankind are more disposed to suffer  while evils are sufferable  than to right themselves by abolishing the forms to which they are accustomed  But when a long train of abuses and usurpations  pursuing invariably the same Object evinces a design to reduce them under absolute Despotism  it is their right  it is their duty  to throw off such Government  and to provide new Guards for their future security   Such has been the patient sufferance of these Colonies  and such is now the necessity which constrains them to alter their former Systems of Government  The history of the present King of Great Britain is a history of repeated injuries and usurpations  all having in direct object the establishment of an absolute Tyranny over these States  To prove this  let Facts be submitted to a candid world  \n",
      "('to', 20)\n",
      "('the', 19)\n",
      "('of', 16)\n",
      "('and', 13)\n",
      "('that', 8)\n",
      "('are', 7)\n",
      "('their', 7)\n",
      "('them', 6)\n",
      "('these', 6)\n",
      "('is', 5)\n",
      "('which', 5)\n",
      "('such', 5)\n",
      "('a', 5)\n",
      "('government', 4)\n",
      "('it', 4)\n",
      "('all', 3)\n",
      "('they', 3)\n",
      "('right', 3)\n",
      "('among', 3)\n",
      "('be', 3)\n",
      "('powers', 3)\n",
      "('its', 2)\n",
      "('causes', 2)\n",
      "('should', 2)\n",
      "('alter', 2)\n",
      "('governments', 2)\n",
      "('for', 2)\n",
      "('happiness', 2)\n",
      "('new', 2)\n",
      "('men', 2)\n",
      "('by', 2)\n",
      "('usurpations', 2)\n",
      "('equal', 2)\n",
      "('long', 2)\n",
      "('form', 2)\n",
      "('with', 2)\n",
      "('rights', 2)\n",
      "('history', 2)\n",
      "('in', 2)\n",
      "('absolute', 2)\n",
      "('object', 2)\n",
      "('mankind', 2)\n",
      "('opinions', 1)\n",
      "('just', 1)\n",
      "('consent', 1)\n",
      "('over', 1)\n",
      "('hath', 1)\n",
      "('invariably', 1)\n",
      "('facts', 1)\n",
      "('earth', 1)\n",
      "('suffer', 1)\n",
      "('forms', 1)\n",
      "('systems', 1)\n",
      "('indeed', 1)\n",
      "('has', 1)\n",
      "('bands', 1)\n",
      "('prudence', 1)\n",
      "('candid', 1)\n",
      "('under', 1)\n",
      "('not', 1)\n",
      "('world', 1)\n",
      "('now', 1)\n",
      "('laying', 1)\n",
      "('this', 1)\n",
      "('abuses', 1)\n",
      "('abolishing', 1)\n",
      "('people', 1)\n",
      "('truths', 1)\n",
      "('reduce', 1)\n",
      "('ends', 1)\n",
      "('likely', 1)\n",
      "('shewn', 1)\n",
      "(\"nature's\", 1)\n",
      "('organizing', 1)\n",
      "('principles', 1)\n",
      "('will', 1)\n",
      "('god', 1)\n",
      "('shall', 1)\n",
      "('liberty', 1)\n",
      "('injuries', 1)\n",
      "('unalienable', 1)\n",
      "('safety', 1)\n",
      "('foundation', 1)\n",
      "('we', 1)\n",
      "('patient', 1)\n",
      "('nature', 1)\n",
      "('states', 1)\n",
      "('let', 1)\n",
      "('pursuit', 1)\n",
      "('separation', 1)\n",
      "('constrains', 1)\n",
      "('on', 1)\n",
      "('great', 1)\n",
      "('created', 1)\n",
      "('institute', 1)\n",
      "('changed', 1)\n",
      "('experience', 1)\n",
      "('sufferance', 1)\n",
      "('or', 1)\n",
      "('duty', 1)\n",
      "('sufferable', 1)\n",
      "('secure', 1)\n",
      "('been', 1)\n",
      "('another', 1)\n",
      "('respect', 1)\n",
      "('from', 1)\n",
      "('prove', 1)\n",
      "('decent', 1)\n",
      "('creator', 1)\n",
      "('disposed', 1)\n",
      "('throw', 1)\n",
      "('accordingly', 1)\n",
      "('station', 1)\n",
      "('entitle', 1)\n",
      "('certain', 1)\n",
      "('themselves', 1)\n",
      "('more', 1)\n",
      "('tyranny', 1)\n",
      "('life', 1)\n",
      "('evinces', 1)\n",
      "('becomes', 1)\n",
      "('pursuing', 1)\n",
      "('but', 1)\n",
      "('instituted', 1)\n",
      "('repeated', 1)\n",
      "('transient', 1)\n",
      "('former', 1)\n",
      "('hold', 1)\n",
      "('than', 1)\n",
      "('present', 1)\n",
      "('king', 1)\n",
      "('evident', 1)\n",
      "('britain', 1)\n",
      "('submitted', 1)\n",
      "('impel', 1)\n",
      "('assume', 1)\n",
      "('while', 1)\n",
      "('future', 1)\n",
      "('accustomed', 1)\n",
      "('light', 1)\n",
      "('design', 1)\n",
      "('declare', 1)\n",
      "('security', 1)\n",
      "('endowed', 1)\n",
      "('dictate', 1)\n",
      "('an', 1)\n",
      "('direct', 1)\n",
      "('as', 1)\n",
      "('despotism', 1)\n",
      "('have', 1)\n",
      "('seem', 1)\n",
      "('any', 1)\n",
      "('evils', 1)\n",
      "('self', 1)\n",
      "('when', 1)\n",
      "('same', 1)\n",
      "('abolish', 1)\n",
      "('guards', 1)\n",
      "('colonies', 1)\n",
      "('establishment', 1)\n",
      "('separate', 1)\n",
      "('effect', 1)\n",
      "('deriving', 1)\n",
      "('most', 1)\n",
      "('connected', 1)\n",
      "('necessity', 1)\n",
      "('destructive', 1)\n",
      "('off', 1)\n",
      "('whenever', 1)\n",
      "('established', 1)\n",
      "('governed', 1)\n",
      "('provide', 1)\n",
      "('train', 1)\n",
      "('requires', 1)\n",
      "('having', 1)\n",
      "('laws', 1)\n"
     ]
    }
   ],
   "source": [
    "Text=\"\"\"\n",
    "bands which have connected them with another, and to assume among the\n",
    "powers of the earth, the separate and equal station to which the Laws\n",
    "of Nature and of Nature's God entitle them, a decent respect to the\n",
    "opinions of mankind requires that they should declare the causes which\n",
    "impel them to the separation.  We hold these truths to be\n",
    "self-evident, that all men are created equal, that they are endowed by\n",
    "their Creator with certain unalienable Rights, that among these are\n",
    "Life, Liberty and the pursuit of Happiness.--That to secure these\n",
    "rights, Governments are instituted among Men, deriving their just\n",
    "powers from the consent of the governed, --That whenever any Form of\n",
    "Government becomes destructive of these ends, it is the Right of the\n",
    "People to alter or to abolish it, and to institute new Government,\n",
    "laying its foundation on such principles and organizing its powers in\n",
    "such form, as to them shall seem most likely to effect their Safety\n",
    "and Happiness. Prudence, indeed, will dictate that Governments long\n",
    "established should not be changed for light and transient causes; and\n",
    "accordingly all experience hath shewn, that mankind are more disposed\n",
    "to suffer, while evils are sufferable, than to right themselves by\n",
    "abolishing the forms to which they are accustomed. But when a long\n",
    "train of abuses and usurpations, pursuing invariably the same Object\n",
    "evinces a design to reduce them under absolute Despotism, it is their\n",
    "right, it is their duty, to throw off such Government, and to provide\n",
    "new Guards for their future security.--Such has been the patient\n",
    "sufferance of these Colonies; and such is now the necessity which\n",
    "constrains them to alter their former Systems of Government. The\n",
    "history of the present King of Great Britain is a history of repeated\n",
    "injuries and usurpations, all having in direct object the\n",
    "establishment of an absolute Tyranny over these States. To prove this,\n",
    "let Facts be submitted to a candid world.\n",
    "\"\"\"\n",
    "\n",
    "# First, we replace the punctuations marks with spaces\n",
    "for char in '-.,\\n;':\n",
    "    Text = Text.replace(char,' ')\n",
    "#print Text\n",
    "print(Text)\n",
    "\n",
    "#convert text to list and remove spaces\n",
    "words_list = Text.split(' ')\n",
    "words_list = [i for i in words_list if i not in ('')]\n",
    "\n",
    "#convert to all words to lowercase\n",
    "words_list = [i.lower() for i in words_list]\n",
    "\n",
    "#define a set with the words\n",
    "words = set(words_list)\n",
    "\n",
    "#count how many times a word appears in the text and save as pairs word and count to list\n",
    "L=[]\n",
    "for word in words:\n",
    "    word_count = 0\n",
    "    for word_list in words_list:\n",
    "        if word == word_list:\n",
    "            word_count+=1\n",
    "    L.append((word,word_count))\n",
    "\n",
    "#sort list from highest to lowest count\n",
    "L.sort(key=lambda tup: tup[1], reverse=True)  \n",
    "\n",
    "#print one pair per line\n",
    "for line in L:\n",
    "    print(line)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# (3) same as 2, but instead of single words, count the number of occurances of **word pairs** i.e.\n",
    "# ('bands','which'),('which','have'),..."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[('of', 'the'), 4]\n",
      "[('it', 'is'), 3]\n",
      "[('and', 'to'), 3]\n",
      "[('of', 'these'), 2]\n",
      "[('that', 'they'), 2]\n",
      "[('of', 'government'), 2]\n",
      "[('history', 'of'), 2]\n",
      "[('they', 'are'), 2]\n",
      "[('is', 'their'), 2]\n",
      "[('to', 'the'), 2]\n",
      "[('them', 'to'), 2]\n",
      "[('to', 'which'), 2]\n",
      "[('and', 'usurpations'), 2]\n",
      "[('to', 'alter'), 2]\n",
      "[('states', 'to'), 1]\n",
      "[('alter', 'their'), 1]\n",
      "[('to', 'assume'), 1]\n",
      "[('form', 'as'), 1]\n",
      "[('and', 'the'), 1]\n",
      "[('which', 'have'), 1]\n",
      "[('absolute', 'despotism'), 1]\n",
      "[('for', 'light'), 1]\n",
      "[('and', 'accordingly'), 1]\n",
      "[('but', 'when'), 1]\n",
      "[('provide', 'new'), 1]\n",
      "[('that', 'mankind'), 1]\n",
      "[('king', 'of'), 1]\n",
      "[('future', 'security'), 1]\n",
      "[('while', 'evils'), 1]\n",
      "[('by', 'abolishing'), 1]\n",
      "[('for', 'their'), 1]\n",
      "[('present', 'king'), 1]\n",
      "[('separation', 'we'), 1]\n",
      "[('such', 'principles'), 1]\n",
      "[('absolute', 'tyranny'), 1]\n",
      "[('just', 'powers'), 1]\n",
      "[('abolishing', 'the'), 1]\n",
      "[('establishment', 'of'), 1]\n",
      "[('rights', 'that'), 1]\n",
      "[('as', 'to'), 1]\n",
      "[('indeed', 'will'), 1]\n",
      "[('their', 'right'), 1]\n",
      "[('facts', 'be'), 1]\n",
      "[('a', 'history'), 1]\n",
      "[('laying', 'its'), 1]\n",
      "[('to', 'effect'), 1]\n",
      "[('right', 'themselves'), 1]\n",
      "[('britain', 'is'), 1]\n",
      "[('we', 'hold'), 1]\n",
      "[('suffer', 'while'), 1]\n",
      "[('security', 'such'), 1]\n",
      "[('same', 'object'), 1]\n",
      "[('evident', 'that'), 1]\n",
      "[('the', 'opinions'), 1]\n",
      "[('laws', 'of'), 1]\n",
      "[('of', 'mankind'), 1]\n",
      "[('are', 'life'), 1]\n",
      "[('form', 'of'), 1]\n",
      "[('their', 'safety'), 1]\n",
      "[('pursuing', 'invariably'), 1]\n",
      "[('patient', 'sufferance'), 1]\n",
      "[('are', 'more'), 1]\n",
      "[('certain', 'unalienable'), 1]\n",
      "[('these', 'rights'), 1]\n",
      "[('be', 'self'), 1]\n",
      "[('having', 'in'), 1]\n",
      "[('are', 'created'), 1]\n",
      "[('that', 'whenever'), 1]\n",
      "[('another', 'and'), 1]\n",
      "[('instituted', 'among'), 1]\n",
      "[('now', 'the'), 1]\n",
      "[('these', 'ends'), 1]\n",
      "[('these', 'truths'), 1]\n",
      "[('of', 'great'), 1]\n",
      "[('a', 'design'), 1]\n",
      "[('with', 'certain'), 1]\n",
      "[('which', 'impel'), 1]\n",
      "[('causes', 'which'), 1]\n",
      "[('such', 'government'), 1]\n",
      "[('opinions', 'of'), 1]\n",
      "[('invariably', 'the'), 1]\n",
      "[('to', 'throw'), 1]\n",
      "[('in', 'such'), 1]\n",
      "[('guards', 'for'), 1]\n",
      "[('light', 'and'), 1]\n",
      "[('entitle', 'them'), 1]\n",
      "[('unalienable', 'rights'), 1]\n",
      "[('assume', 'among'), 1]\n",
      "[('evils', 'are'), 1]\n",
      "[('governments', 'long'), 1]\n",
      "[('the', 'necessity'), 1]\n",
      "[('an', 'absolute'), 1]\n",
      "[('hath', 'shewn'), 1]\n",
      "[('to', 'them'), 1]\n",
      "[('disposed', 'to'), 1]\n",
      "[('changed', 'for'), 1]\n",
      "[('that', 'to'), 1]\n",
      "[('and', 'of'), 1]\n",
      "[('constrains', 'them'), 1]\n",
      "[('injuries', 'and'), 1]\n",
      "[('all', 'having'), 1]\n",
      "[('these', 'states'), 1]\n",
      "[('separate', 'and'), 1]\n",
      "[('causes', 'and'), 1]\n",
      "[('their', 'creator'), 1]\n",
      "[('be', 'submitted'), 1]\n",
      "[('mankind', 'requires'), 1]\n",
      "[('created', 'equal'), 1]\n",
      "[('all', 'men'), 1]\n",
      "[('long', 'established'), 1]\n",
      "[('will', 'dictate'), 1]\n",
      "[('pursuit', 'of'), 1]\n",
      "[('the', 'causes'), 1]\n",
      "[('the', 'establishment'), 1]\n",
      "[('right', 'it'), 1]\n",
      "[('these', 'colonies'), 1]\n",
      "[('rights', 'governments'), 1]\n",
      "[('or', 'to'), 1]\n",
      "[('to', 'provide'), 1]\n",
      "[('their', 'just'), 1]\n",
      "[('on', 'such'), 1]\n",
      "[('government', 'the'), 1]\n",
      "[('necessity', 'which'), 1]\n",
      "[('with', 'another'), 1]\n",
      "[('consent', 'of'), 1]\n",
      "[('earth', 'the'), 1]\n",
      "[('a', 'candid'), 1]\n",
      "[('equal', 'that'), 1]\n",
      "[('abuses', 'and'), 1]\n",
      "[('that', 'governments'), 1]\n",
      "[('people', 'to'), 1]\n",
      "[('and', 'happiness'), 1]\n",
      "[('safety', 'and'), 1]\n",
      "[('dictate', 'that'), 1]\n",
      "[('to', 'suffer'), 1]\n",
      "[('reduce', 'them'), 1]\n",
      "[('experience', 'hath'), 1]\n",
      "[('be', 'changed'), 1]\n",
      "[('them', 'with'), 1]\n",
      "[('great', 'britain'), 1]\n",
      "[('their', 'former'), 1]\n",
      "[('to', 'a'), 1]\n",
      "[('tyranny', 'over'), 1]\n",
      "[('such', 'form'), 1]\n",
      "[('from', 'the'), 1]\n",
      "[('should', 'declare'), 1]\n",
      "[('off', 'such'), 1]\n",
      "[('it', 'and'), 1]\n",
      "[('are', 'sufferable'), 1]\n",
      "[('declare', 'the'), 1]\n",
      "[('accustomed', 'but'), 1]\n",
      "[('institute', 'new'), 1]\n",
      "[('to', 'institute'), 1]\n",
      "[('in', 'direct'), 1]\n",
      "[('that', 'among'), 1]\n",
      "[('and', 'such'), 1]\n",
      "[('a', 'long'), 1]\n",
      "[('powers', 'in'), 1]\n",
      "[('and', 'equal'), 1]\n",
      "[('are', 'accustomed'), 1]\n",
      "[('of', 'an'), 1]\n",
      "[(\"nature's\", 'god'), 1]\n",
      "[('are', 'endowed'), 1]\n",
      "[('powers', 'from'), 1]\n",
      "[('likely', 'to'), 1]\n",
      "[('to', 'prove'), 1]\n",
      "[('equal', 'station'), 1]\n",
      "[('the', 'people'), 1]\n",
      "[('the', 'forms'), 1]\n",
      "[('governments', 'are'), 1]\n",
      "[('which', 'constrains'), 1]\n",
      "[('their', 'future'), 1]\n",
      "[('and', 'organizing'), 1]\n",
      "[('government', 'and'), 1]\n",
      "[('shall', 'seem'), 1]\n",
      "[('new', 'guards'), 1]\n",
      "[('long', 'train'), 1]\n",
      "[('these', 'are'), 1]\n",
      "[('impel', 'them'), 1]\n",
      "[('the', 'consent'), 1]\n",
      "[('new', 'government'), 1]\n",
      "[('the', 'history'), 1]\n",
      "[('organizing', 'its'), 1]\n",
      "[('repeated', 'injuries'), 1]\n",
      "[('to', 'right'), 1]\n",
      "[('this', 'let'), 1]\n",
      "[('train', 'of'), 1]\n",
      "[('government', 'becomes'), 1]\n",
      "[('their', 'duty'), 1]\n",
      "[('transient', 'causes'), 1]\n",
      "[('deriving', 'their'), 1]\n",
      "[('forms', 'to'), 1]\n",
      "[('the', 'governed'), 1]\n",
      "[('should', 'not'), 1]\n",
      "[('respect', 'to'), 1]\n",
      "[('than', 'to'), 1]\n",
      "[('the', 'right'), 1]\n",
      "[('station', 'to'), 1]\n",
      "[('themselves', 'by'), 1]\n",
      "[('of', \"nature's\"), 1]\n",
      "[('them', 'under'), 1]\n",
      "[('endowed', 'by'), 1]\n",
      "[('shewn', 'that'), 1]\n",
      "[('of', 'happiness'), 1]\n",
      "[('sufferance', 'of'), 1]\n",
      "[('despotism', 'it'), 1]\n",
      "[('the', 'separate'), 1]\n",
      "[('submitted', 'to'), 1]\n",
      "[('prudence', 'indeed'), 1]\n",
      "[('let', 'facts'), 1]\n",
      "[('to', 'abolish'), 1]\n",
      "[('by', 'their'), 1]\n",
      "[('the', 'pursuit'), 1]\n",
      "[('destructive', 'of'), 1]\n",
      "[('alter', 'or'), 1]\n",
      "[('has', 'been'), 1]\n",
      "[('accordingly', 'all'), 1]\n",
      "[('government', 'laying'), 1]\n",
      "[('happiness', 'that'), 1]\n",
      "[('powers', 'of'), 1]\n",
      "[('former', 'systems'), 1]\n",
      "[('effect', 'their'), 1]\n",
      "[('ends', 'it'), 1]\n",
      "[('been', 'the'), 1]\n",
      "[('seem', 'most'), 1]\n",
      "[('is', 'the'), 1]\n",
      "[('requires', 'that'), 1]\n",
      "[('life', 'liberty'), 1]\n",
      "[('colonies', 'and'), 1]\n",
      "[('throw', 'off'), 1]\n",
      "[('principles', 'and'), 1]\n",
      "[('men', 'deriving'), 1]\n",
      "[('under', 'absolute'), 1]\n",
      "[('to', 'reduce'), 1]\n",
      "[('the', 'separation'), 1]\n",
      "[('god', 'entitle'), 1]\n",
      "[('established', 'should'), 1]\n",
      "[('to', 'secure'), 1]\n",
      "[('duty', 'to'), 1]\n",
      "[('among', 'these'), 1]\n",
      "[('whenever', 'any'), 1]\n",
      "[('men', 'are'), 1]\n",
      "[('usurpations', 'pursuing'), 1]\n",
      "[('is', 'a'), 1]\n",
      "[('happiness', 'prudence'), 1]\n",
      "[('design', 'to'), 1]\n",
      "[('are', 'instituted'), 1]\n",
      "[('any', 'form'), 1]\n",
      "[('its', 'powers'), 1]\n",
      "[('abolish', 'it'), 1]\n",
      "[('nature', 'and'), 1]\n",
      "[('candid', 'world'), 1]\n",
      "[('when', 'a'), 1]\n",
      "[('among', 'the'), 1]\n",
      "[('object', 'the'), 1]\n",
      "[('and', 'transient'), 1]\n",
      "[('which', 'they'), 1]\n",
      "[('they', 'should'), 1]\n",
      "[('to', 'be'), 1]\n",
      "[('foundation', 'on'), 1]\n",
      "[('the', 'laws'), 1]\n",
      "[('its', 'foundation'), 1]\n",
      "[('the', 'present'), 1]\n",
      "[('liberty', 'and'), 1]\n",
      "[('not', 'be'), 1]\n",
      "[('is', 'now'), 1]\n",
      "[('decent', 'respect'), 1]\n",
      "[('secure', 'these'), 1]\n",
      "[('the', 'patient'), 1]\n",
      "[('most', 'likely'), 1]\n",
      "[('self', 'evident'), 1]\n",
      "[('mankind', 'are'), 1]\n",
      "[('evinces', 'a'), 1]\n",
      "[('which', 'the'), 1]\n",
      "[('the', 'powers'), 1]\n",
      "[('sufferable', 'than'), 1]\n",
      "[('the', 'same'), 1]\n",
      "[('a', 'decent'), 1]\n",
      "[('more', 'disposed'), 1]\n",
      "[('governed', 'that'), 1]\n",
      "[('hold', 'these'), 1]\n",
      "[('among', 'men'), 1]\n",
      "[('such', 'has'), 1]\n",
      "[('that', 'all'), 1]\n",
      "[('of', 'nature'), 1]\n",
      "[('them', 'shall'), 1]\n",
      "[('have', 'connected'), 1]\n",
      "[('becomes', 'destructive'), 1]\n",
      "[('them', 'a'), 1]\n",
      "[('object', 'evinces'), 1]\n",
      "[('connected', 'them'), 1]\n",
      "[('such', 'is'), 1]\n",
      "[('bands', 'which'), 1]\n",
      "[('usurpations', 'all'), 1]\n",
      "[('of', 'abuses'), 1]\n",
      "[('over', 'these'), 1]\n",
      "[('of', 'repeated'), 1]\n",
      "[('right', 'of'), 1]\n",
      "[('truths', 'to'), 1]\n",
      "[('the', 'earth'), 1]\n",
      "[('systems', 'of'), 1]\n",
      "[('creator', 'with'), 1]\n",
      "[('all', 'experience'), 1]\n",
      "[('prove', 'this'), 1]\n",
      "[('direct', 'object'), 1]\n"
     ]
    }
   ],
   "source": [
    "#find list of word pairs\n",
    "list_words_pairs = []\n",
    "for i in range(len(words_list)-1):\n",
    "    list_words_pairs.append((words_list[i],words_list[i+1]))\n",
    "    \n",
    "#make set and count number of times each pair shows up\n",
    "L = []\n",
    "words_pair = set(list_words_pairs)\n",
    "for word_pair in words_pair:\n",
    "    pair_count = 0\n",
    "    for list_word_pairs in list_words_pairs:\n",
    "        if word_pair == list_word_pairs:\n",
    "            pair_count = pair_count + 1\n",
    "    L.append([word_pair,pair_count])\n",
    "    \n",
    "#sort list from highest to lowest count\n",
    "L.sort(key=lambda tup: tup[1], reverse=True)  \n",
    "\n",
    "#print one pair per line\n",
    "for line in L:\n",
    "    print(line)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(4) For the list `l =  [ 6, -5, 3, -2, 0, 8, -9, -7 ]`, return the numbers which are greater than the average (of these numbers)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-0.75\n",
      "[6, 3, 0, 8]\n"
     ]
    }
   ],
   "source": [
    "l =  [ 6, -5, 3, -2, 0, 8, -9, -7 ]\n",
    "\n",
    "#find average\n",
    "l_avg = sum(l)/float(len(l))\n",
    "print(l_avg)\n",
    "\n",
    "#find numbers greater than the average\n",
    "N_greater = [i for i in l if i>l_avg]\n",
    "print(N_greater)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(5) for the tuples (2, 5, 3, 7, 10, 20, 54, 89) and (15, 16, 3, 37, 54, 21, 20, 5) return a sorted tuple that contains\n",
    "only the elements common to both the tuples (use sets)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(3, 5, 20, 54)\n",
      "<type 'tuple'>\n"
     ]
    }
   ],
   "source": [
    "#define both seets\n",
    "set_a = set([2, 5, 3, 7, 10, 20, 54, 89])\n",
    "set_b = set([15, 16, 3, 37, 54, 21, 20, 5])\n",
    "\n",
    "#find elements in common and sort\n",
    "set_c = tuple(sorted(set_a & set_b))\n",
    "\n",
    "print(set_c)\n",
    "print(type(set_c))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(6) calculate the average word length for the text\n",
    "\n",
    "> TEXT =\n",
    "> On a dark desert highway, cool wind in my hair\n",
    "> Warm smell of colitas, rising up through the air\n",
    "> Up ahead in the distance, I saw a shimmering light\n",
    "> My head grew heavy and my sight grew dim\n",
    "> I had to stop for the night\n",
    "> There she stood in the doorway;\n",
    "> I heard the mission bell\n",
    "> And I was thinking to myself,\n",
    "> \"This could be Heaven or this could be Hell\"\n",
    "> Then she lit up a candle and she showed me the way\n",
    "> \n",
    "\n",
    "Average word length is the sum of all the lengths of the word tokens in the text, divided by the number of word tokens\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " On a dark desert highway  cool wind in my hair Warm smell of colitas  rising up through the air Up ahead in the distance   I saw a shimmering light My head grew heavy and my sight grew dim I had to stop for the night There she stood in the doorway   I heard the mission bell And I was thinking to myself   This could be Heaven or this could be Hell  Then she lit up a candle  and she showed me the way \n",
      "3.72289156627\n"
     ]
    }
   ],
   "source": [
    "#define text\n",
    "TEXT = \"\"\"\n",
    "On a dark desert highway, cool wind in my hair Warm smell of colitas, rising up through the air Up ahead in the distance, \n",
    "I saw a shimmering light My head grew heavy and my sight grew dim I had to stop for the night There she stood in the doorway; \n",
    "I heard the mission bell And I was thinking to myself, \"This could be Heaven or this could be Hell\" Then she lit up a candle \n",
    "and she showed me the way\n",
    "\"\"\"\n",
    "\n",
    "#recycle code from above\n",
    "# First, we replace the punctuations marks with spaces\n",
    "list_char = ['-','.',',','\\n',';','\"']\n",
    "for char in list_char:\n",
    "    TEXT = TEXT.replace(char,' ')\n",
    "#print Text\n",
    "print(TEXT)\n",
    "\n",
    "#convert text to list and remove spaces\n",
    "words_list = TEXT.split(' ')\n",
    "words_list = [i for i in words_list if i not in ('')]\n",
    "    \n",
    "#find average word length\n",
    "total_word_L = len(''.join(words_list))\n",
    "avg_word_L = total_word_L/float(len(words_list))\n",
    "print(avg_word_L)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(7) Using the same text as in the last one, remove all punctuation and output the words in sorted alphabetical order. Save this output as a CSV file with each word separated from the other by the delimiter(comma)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " On a dark desert highway  cool wind in my hair Warm smell of colitas  rising up through the air Up ahead in the distance   I saw a shimmering light My head grew heavy and my sight grew dim I had to stop for the night There she stood in the doorway   I heard the mission bell And I was thinking to myself   This could be Heaven or this could be Hell  Then she lit up a candle  and she showed me the way \n"
     ]
    }
   ],
   "source": [
    "#import libraries\n",
    "import csv\n",
    "\n",
    "#define text\n",
    "TEXT = \"\"\"\n",
    "On a dark desert highway, cool wind in my hair Warm smell of colitas, rising up through the air Up ahead in the distance, \n",
    "I saw a shimmering light My head grew heavy and my sight grew dim I had to stop for the night There she stood in the doorway; \n",
    "I heard the mission bell And I was thinking to myself, \"This could be Heaven or this could be Hell\" Then she lit up a candle \n",
    "and she showed me the way\n",
    "\"\"\"\n",
    "\n",
    "#recycle code from above\n",
    "# First, we replace the punctuations marks with spaces\n",
    "list_char = ['-','.',',','\\n',';','\"']\n",
    "for char in list_char:\n",
    "    TEXT = TEXT.replace(char,' ')\n",
    "#print Text\n",
    "print(TEXT)\n",
    "\n",
    "#convert text to list and remove spaces\n",
    "words_list = TEXT.split(' ')\n",
    "words_list = [i for i in words_list if i not in ('')]\n",
    "    \n",
    "#sort in alphabetical order\n",
    "words_list = sorted(words_list,key=str.lower)\n",
    "\n",
    "#output as csv file\n",
    "outdir = 'C:/Users/rmartinez4/Box/DSE Masters/Fall 2019/day_1_python_and_unix/day_1_python_and_unix'\n",
    "with open(outdir+'/7_text.csv', 'wb') as myfile:\n",
    "    wr = csv.writer(myfile,delimiter=',')\n",
    "    wr.writerow(words_list)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(8) Read the text from the above separated csv file and return a dictionary of (letter:count) pair\n",
    "that counts the number of times each letter appears in that line."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'A': 1, 'I': 4, 'H': 2, 'M': 1, 'O': 1, 'U': 1, 'T': 3, 'W': 1, 'a': 24, 'c': 6, 'b': 3, 'e': 33, 'd': 18, 'g': 10, 'f': 3, 'i': 24, 'h': 29, 'k': 2, 'm': 10, 'l': 14, 'o': 18, 'n': 18, 'p': 4, 's': 20, 'r': 15, 'u': 5, 't': 20, 'w': 9, 'v': 2, 'y': 8}\n"
     ]
    }
   ],
   "source": [
    "#import libraries\n",
    "import csv\n",
    "\n",
    "#read csv and assign to a list\n",
    "outdir = 'C:/Users/rmartinez4/Box/DSE Masters/Fall 2019/day_1_python_and_unix/day_1_python_and_unix'\n",
    "file_name = '/7_text.csv'\n",
    "with open(outdir+file_name) as csv_file:\n",
    "    csv_reader = csv.reader(csv_file, delimiter=',')\n",
    "    lines=[]\n",
    "    for line in csv_reader:\n",
    "        lines=lines+line\n",
    "\n",
    "#create a set of letters\n",
    "all_letters = ''.join(lines)\n",
    "set_letters = set(all_letters)\n",
    "\n",
    "#count how many times a letter appears from the set and assign to dictionary\n",
    "letter_dict={}\n",
    "for set_letter in set_letters:\n",
    "    letter_dict[set_letter] = sum([set_letter in i for i in all_letters])\n",
    "\n",
    "#print dictionary\n",
    "print(letter_dict)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "None\n",
      "True\n"
     ]
    }
   ],
   "source": [
    "#(9) Take as an input an array of integers, and return true if the array contains a 5 immediately after another 5 \n",
    "#somewhere.\n",
    "A=[1,5,1,6,5,3,5,2]\n",
    "B=[1,2,3,4,5,5,6,7,8,9]\n",
    "\n",
    "#define function\n",
    "def check_back2back_number(input_array, number):\n",
    "    for i in range(len(input_array)-1):\n",
    "        if (input_array[i] == number) & (input_array[i+1] == number):\n",
    "            return True\n",
    "            break\n",
    "        else:\n",
    "            continue\n",
    "\n",
    "#check array A\n",
    "check_five = check_back2back_number(A,5)\n",
    "print(check_five)\n",
    "        \n",
    "#check array B\n",
    "check_five = check_back2back_number(B,5)\n",
    "print(check_five)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(10) Write  a program that takes in a positive number (in some variable, say `i`) and computes the sum of all the number\n",
    "between 0 and that number (inclusive). \n",
    "\n",
    "* Do it using a for loop\n",
    "* Do it in one line using the function `sum` and list comprehension."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Method #1: 50005000\n",
      "Method #2: 50005000\n"
     ]
    }
   ],
   "source": [
    "number = 10000\n",
    "\n",
    "#Method 1 - For loop\n",
    "sum_list = 0\n",
    "for num in range(number+1):\n",
    "    sum_list = sum_list + num\n",
    "print('Method #1: ' + str(sum_list))\n",
    "\n",
    "#Method 2 - List comprehension\n",
    "total_sum = sum([i for i in range(number+1)])\n",
    "print('Method #2: ' + str(sum_list))\n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(11) for the text in file BrownNews.txt (~/DSE200/data/NLTK/BrownNews.txt), \n",
    "find the distribution of the second letter in each word. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced   no evidence   that any irregularities took place  The jury further said in term end presentments that the City Executive Committee   which had over all charge of the election     deserves the praise and thanks of the City of Atlanta   for the manner in which the election was conducted  The September October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible   irregularities   in the hard fought primary which was won by Mayor nominate Ivan Allen Jr     Only a relative handful of such reports was received     the jury said     considering the widespread interest in the election   the number of voters and the size of this city    The jury said it did find that many of Georgia's registration and election laws   are outmoded or inadequate and often ambiguous    It recommended that Fulton legislators act   to have these laws studied and revised to the end of modernizing and improving them    The grand jury commented on a number of other topics   among them the Atlanta and Fulton County purchasing departments which it said   are well operated and follow generally accepted practices which inure to the best interest of both governments    Merger proposedHowever   the jury said it believes   these two offices should be combined to achieve greater efficiency and reduce the cost of administration    The City Purchasing Department   the jury said     is lacking in experienced clerical personnel as a result of city personnel policies    \n",
      "a -> word with less than two letters\n",
      "a -> word with less than two letters\n",
      "a -> word with less than two letters\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYIAAAEWCAYAAABrDZDcAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDIuMi4zLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvIxREBQAAHzxJREFUeJzt3XuYHFW57/HvjxDuAQwZNFyDCApbIWiIKBtFLh5A3OA+KLJFo4IBBVEEFRQ1cjnAdkv07KNiuEgAERBFEGULAiHcYQJJCERJuIdEMgQiCSiQ5D1/1BqtNN0z1TNT3ZnU7/M8/UzdVq23qmv6rVXVvUoRgZmZVdca7Q7AzMzay4nAzKzinAjMzCrOicDMrOKcCMzMKs6JwMys4pwI2kDSuZK+NUDr2krSUklD0vgUSUcOxLrT+q6XNG6g1tdEvadLek7SX1pdd39JekLSPg3mXSTp9FbH1Ejt8bMq6Gn/tZOkkPSWdsdRBieCAZYO4r9JWiJpsaQ7JR0t6R/7OiKOjojTCq6rx3+IiHgqIjaIiOUDEPsESZfWrH//iJjc33U3GceWwAnAjhHxplbWvSqpff8ljUofRmsOVB0DefzY4OVEUI4PR8QwYGvgLODrwAUDXclAfiCsYrYGFkXEwnYHsjpZjY+XAVXF/eREUKKI+GtEXAscCoyT9HZY+fKApBGSrkuth+cl3SZpDUmXAFsBv01N96/lzgiPkPQUcHODs8RtJd0r6a+SrpE0PNW1p6R5+Ri7zzol7Qd8Azg01Tcjzf/HpaYU1ymSnpS0UNLFkjZK87rjGCfpqXRZ55uN9o2kjVL5rrS+U9L69wFuBDZLcVxUp2zdfZbmbSbpV2m9j0s6LlduiKRvSHo0tdimpdYHkt4r6b60z+6T9N5cuSmSTpN0Ryp3g6QRufmfTNuwqKdtbrAfDpQ0Pdd63ClNf937D0xNxRanae9Jy35W0mxJL0j6g6Stc+sPScdImgPMqVP/SsdPb9taNP4076Tcvn5Y0kdqyn4uxd09/5252aMlzUzvxxWS1mlQ/5OS3pWGD0/bsmMaP1LSb9Lw2pJ+IGl+ev1A0tpp3p6S5kn6urJLkT9L078qaUFa/rON9sFqISL8GsAX8ASwT53pTwGfT8MXAaen4TOBc4Gh6bUHoHrrAkYBAVwMrA+sm5u2ZlpmCvAM8Pa0zK+AS9O8PYF5jeIFJnQvm5s/BTgyDX8WmAu8GdgA+DVwSU1s56W4dgZeAXZosJ8uBq4BhqWyjwBHNIqzpmzdfUZ2YjMN+DawVorzMeB/pXJfBR4E3pqW3xnYBBgOvAB8ElgTOCyNb5LbB48C26dtmwKclebtCCwF3gesDZwDLKt3DNR5798JLATeDQwBxqX3Y+1e3v81c9MOTu/JDin2U4A7c/ODLLEOB9atE89K6+xpW+uU7S3+jwKbpfflUOAlYGRu3jPArum9eAuwdW67701lhwOzgaN7OI5OSMOTUuyfz807Pg2fCtwNbAp0AHcCp+WOt2XA2ek9XBfYD3iWf/4fXZb201va/RlTxsstgtaZT3ZQ13oNGEn2T/BaRNwW6ejswYSIeCki/tZg/iURMSsiXgK+BXxMA3Mz8BPAORHxWEQsBU4GPq6VWyPfjYi/RcQMYAbZh+1KUiyHAidHxJKIeAL4PtkHcRGN9tmuQEdEnBoRr0bEY2SJ6eOp3JHAKRHx58jMiIhFwIeAORFxSUQsi4hfAH8CPpyr82cR8Uja51cCo9P0Q4DrImJqRLxCtr9XFNyOzwE/jYh7ImJ5ZPdiXgF2K1ge4CjgzIiYHRHLgP9Ddja9dW6ZMyPi+R6Ol1qNtrWp+CPilxExPyJWRMQVZC2SsanskcB/RsR96b2YGxFP5tb9f1PZ54Hf9hDDrcD70/AeZCcJ3ePvT/MhO3ZPjYiFEdEFfJeVj7cVwHci4pW03R9L+6H7/2hC4901+DkRtM7mwPN1pn+P7IzuBkmPSTqpwLqebmL+k2RnzQ2b903YLK0vv+41gTfmpuW/5fMyWcuh1giyM/badW1eMI5G+2xrsktKi7tfZJe7uuPbkuyMsVbtdtWLp9F2bUZuf6cPjUUFt2Nr4ISaeLdM6yxqa+CHufLPk51h52Pv7XipVeQ97K67YfySPpW7bLSY7Oy6+zhs9F40G8OtwB6S3kTWKrkC2F3SKGAjYHpart6xm9/PXRHx99z4Su8rrz8+VitOBC0gaVeyf8zba+elM+ITIuLNZGegX5G0d/fsBqvsrcWwZW54K7Iz6OfImubr5eIaQtZMLrre+WT//Pl1LyNrQjfjuRRT7bqeKVK4h332NPB4RGycew2LiANS0aeBbeussna7molnAbn9LWk9sstNRTwNnFET73qpRQKvfz/qvT9PA0fVrGPdiLizl3IDoWH8qUVyHnAs2SW2jYFZZEmqu2y996IpETGXLFEcB0yNiCVkSWQ8cHtEdLfO6h278/Orqln1Su9rWn615URQIkkbSjoQuJzs2vuDdZY5UNJbJAl4EVieXpB9wL65D1UfLmnH9KF0KnBVZF8PfARYR9KHJA0lu568dq7cs8Ao5b7qWuMXwPGStpG0AdlliCvSJYnCUixXAmdIGpY+NL4CXNpzyUwP++xe4MV0029dZTeH354SMcD5wGmStlNmJ0mbAL8Htpf0H5LWlHQo2bX/6wqEcxVwoKR/lbQW2f4u+n91HnC0pHeneNZP782wNL/2/e8iu4SRn3YucLKkf0n7ZiNJHy1Yf3/1FP/6ZB+uXSmuz5C1CLqdD5wo6V2p7FtqLmc141ayhNN9GWhKzThkx+4pkjqU3fz+Nj0fb1cCn879H32nj7ENCk4E5fitpCVkZz3fJLuB+JkGy24H/JHshuNdwI8jYkqadybZwbtY0olN1H8J2U3JvwDrkJ0tERF/Bb5A9k/4DFkLIf8tol+mv4sk3V9nvRemdU8FHgf+Dnyxibjyvpjqf4yspXRZWn8RdfdZSjAfJrue/DhZy+N8sksEkL0PVwI3kCWQC8huoC4CDiT77cIi4GvAgRHxXG+BRMRDwDEp/gVkN5nn9Vjon2U7ya6z/79Ubi7w6dwiK73/EfEycAZwR5q2W0RcTXaT83JJL5Kdde9fpP7+6in+iHiY7L7PXWQJ7R3AHbmyv0zbchmwBPgN9e+hFXEr2ZcOpjYYBzgd6ARmkn1h4P40rdG2XQ/8ALg5bdfNfYxtUOj+doqZmVWUWwRmZhXnRGBmVnFOBGZmFedEYGZWcYOic6URI0bEqFGj2h2GmdmgMm3atOcioqO35QZFIhg1ahSdnZ3tDsPMbFCRVOgX0b40ZGZWcU4EZmYV50RgZlZxTgRmZhXnRGBmVnFOBGZmFedEYGZWcU4EZmYV50RgZlZxg+KXxf0x8cZH+lz2+H23H8BIzMxWTW4RmJlVnBOBmVnFORGYmVWcE4GZWcU5EZiZVVzpiUDSEEkPSLoujW8j6R5JcyRdIWmtsmMwM7PGWtEi+BIwOzd+NjAxIrYDXgCOaEEMZmbWQKmJQNIWwIeA89O4gL2Aq9Iik4GDy4zBzMx6VnaL4AfA14AVaXwTYHFELEvj84DNS47BzMx6UFoikHQgsDAipuUn11k0GpQfL6lTUmdXV1cpMZqZWbktgt2Bf5P0BHA52SWhHwAbS+ru2mILYH69whExKSLGRMSYjo6OEsM0M6u20hJBRJwcEVtExCjg48DNEfEJ4BbgkLTYOOCasmIwM7PeteN3BF8HviJpLtk9gwvaEIOZmSUt6X00IqYAU9LwY8DYVtRrZma98y+LzcwqzonAzKzinAjMzCrOicDMrOKcCMzMKs6JwMys4pwIzMwqzonAzKzinAjMzCrOicDMrOKcCMzMKs6JwMys4pwIzMwqzonAzKzinAjMzCrOicDMrOLKfHj9OpLulTRD0kOSvpumXyTpcUnT02t0WTGYmVnvynxC2SvAXhGxVNJQ4HZJ16d5X42Iq0qs28zMCiotEUREAEvT6ND0irLqMzOzvin1HoGkIZKmAwuBGyPinjTrDEkzJU2UtHaDsuMldUrq7OrqKjNMM7NKKzURRMTyiBgNbAGMlfR24GTgbcCuwHDg6w3KToqIMRExpqOjo8wwzcwqrSXfGoqIxcAUYL+IWBCZV4CfAWNbEYOZmdVX5reGOiRtnIbXBfYB/iRpZJom4GBgVlkxmJlZ78r81tBIYLKkIWQJ58qIuE7SzZI6AAHTgaNLjMHMzHpR5reGZgK71Jm+V1l1mplZ8/zLYjOzinMiMDOrOCcCM7OKcyIwM6s4JwIzs4pzIjAzqzgnAjOzinMiMDOrOCcCM7OKcyIwM6s4JwIzs4pzIjAzqzgnAjOzinMiMDOrOCcCM7OKcyIwM6u4Mh9VuY6keyXNkPSQpO+m6dtIukfSHElXSFqrrBjMzKx3ZbYIXgH2ioidgdHAfpJ2A84GJkbEdsALwBElxmBmZr0oLRFEZmkaHZpeAewFXJWmTyZ7gL2ZmbVJqfcIJA2RNB1YCNwIPAosjohlaZF5wOYNyo6X1Cmps6urq8wwzcwqrdREEBHLI2I0sAUwFtih3mINyk6KiDERMaajo6PMMM3MKq0l3xqKiMXAFGA3YGNJa6ZZWwDzWxGDmZnVV+a3hjokbZyG1wX2AWYDtwCHpMXGAdeUFYOZmfVuzd4X6bORwGRJQ8gSzpURcZ2kh4HLJZ0OPABcUGIMZmbWi9ISQUTMBHapM/0xsvsFZma2CvAvi83MKs6JwMys4pwIzMwqzonAzKziyvzWUOVNvPGRPpc9ft/tBzASM7PG3CIwM6s4JwIzs4pzIjAzqzgnAjOzivPNYlst+Ma8Wd+5RWBmVnFOBGZmFedEYGZWcU4EZmYV55vFthLfdDWrnjKfULalpFskzZb0kKQvpekTJD0jaXp6HVBWDGZm1rsyWwTLgBMi4n5Jw4Bpkm5M8yZGxH+VWLeZmRVU5hPKFgAL0vASSbOBzcuqz8zM+qYlN4sljSJ7bOU9adKxkmZKulDSG1oRg5mZ1Vd6IpC0AfAr4MsR8SLwE2BbYDRZi+H7DcqNl9QpqbOrq6vsMM3MKqvURCBpKFkS+HlE/BogIp6NiOURsQI4jwYPso+ISRExJiLGdHR0lBmmmVmllfmtIQEXALMj4pzc9JG5xT4CzCorBjMz612hm8WSboqIvXubVmN34JPAg5Kmp2nfAA6TNBoI4AngqKajNjOzAdNjIpC0DrAeMCLd1FWatSGwWU9lI+L23PJ5v+9DnGZmVpLeWgRHAV8m+9Cfxj8/2F8EflRiXGZm1iI9JoKI+CHwQ0lfjIj/blFMZmbWQoXuEUTEf0t6LzAqXyYiLi4pLjMza5GiN4svIfvu/3RgeZocgBOBmdkgV7SLiTHAjhERZQZjZmatV/R3BLOAN5UZiJmZtUfRFsEI4GFJ9wKvdE+MiH8rJSozM2uZoolgQplBmJlZ+xT91tCtZQdiZmbtUfRbQ0vIviUEsBYwFHgpIjYsK7BVQX8e22hmNlgUbREMy49LOpgGvYaamdng0qfeRyPiN8BeAxyLmZm1QdFLQ/+eG12D7HcF/k2BmdlqoOi3hj6cG15G1n30QQMejZmZtVzRewSfKTsQGzi+yW1mzSh0j0DSFpKulrRQ0rOSfiVpi7KDMzOz8hW9Wfwz4Fqy5xJsDvw2TWtI0paSbpE0W9JDkr6Upg+XdKOkOenvG/qzAWZm1j9FE0FHRPwsIpal10VAb0+UXwacEBE7ALsBx0jaETgJuCkitgNuSuNmZtYmRRPBc5IOlzQkvQ4HFvVUICIWRMT9aXgJMJusNXEQMDktNhk4uG+hm5nZQCiaCD4LfAz4C7AAOAQofANZ0ihgF+Ae4I0RsQCyZAFs2qDMeEmdkjq7urqKVmVmZk0qmghOA8ZFREdEbEqWGCYUKShpA+BXwJcj4sWigUXEpIgYExFjOjp6uwplZmZ9VTQR7BQRL3SPRMTzZGf4PZI0lCwJ/Dwifp0mPytpZJo/EljYXMhmZjaQiiaCNfLf7pE0nF5+gyBJwAXA7Ig4JzfrWmBcGh4HXFM8XDMzG2hFf1n8feBOSVeRdS3xMeCMXsrsDnwSeFDS9DTtG8BZwJWSjgCeAj7adNRmZjZgiv6y+GJJnWQdzQn494h4uJcyt6dl69m7qSjNzKw0RVsEpA/+Hj/8zcxs8OlTN9RmZrb6cCIwM6s4JwIzs4pzIjAzqzgnAjOzinMiMDOrOCcCM7OKcyIwM6u4wj8os9YajM8d7m/Mx++7/QBFYmbNcIvAzKzinAjMzCrOicDMrOKcCMzMKs6JwMys4pwIzMwqrrREIOlCSQslzcpNmyDpGUnT0+uAsuo3M7NiymwRXATsV2f6xIgYnV6/L7F+MzMroLREEBFTgefLWr+ZmQ2MdtwjOFbSzHTp6A2NFpI0XlKnpM6urq5WxmdmVimtTgQ/AbYFRgMLgO83WjAiJkXEmIgY09HR0ar4zMwqp6WJICKejYjlEbECOA8Y28r6zczs9VqaCCSNzI1+BJjVaFkzM2uN0noflfQLYE9ghKR5wHeAPSWNBgJ4AjiqrPrNzKyY0hJBRBxWZ/IFZdVnZmZ9418Wm5lVnBOBmVnFORGYmVWcE4GZWcU5EZiZVZwTgZlZxTkRmJlVnBOBmVnFORGYmVWcE4GZWcU5EZiZVZwTgZlZxTkRmJlVnBOBmVnFORGYmVVcaYkgPZx+oaRZuWnDJd0oaU762/Dh9WZm1hpltgguAvarmXYScFNEbAfclMbNzKyNSksEETEVeL5m8kHA5DQ8GTi4rPrNzKyYVt8jeGNELABIfzdttKCk8ZI6JXV2dXW1LEAzs6pZZW8WR8SkiBgTEWM6OjraHY6Z2Wqr1YngWUkjAdLfhS2u38zMarQ6EVwLjEvD44BrWly/mZnVKPPro78A7gLeKmmepCOAs4B9Jc0B9k3jZmbWRmuWteKIOKzBrL3LqtMGt4k3PjLo6j1+3+0Hbd1m3VbZm8VmZtYaTgRmZhXnRGBmVnFOBGZmFedEYGZWcU4EZmYV50RgZlZxTgRmZhXnRGBmVnFOBGZmFedEYGZWcU4EZmYV50RgZlZxTgRmZhXnRGBmVnFOBGZmFVfag2l6IukJYAmwHFgWEWPaEYeZmbUpESQfiIjn2li/mZnhS0NmZpXXrkQQwA2SpkkaX28BSeMldUrq7OrqanF4ZmbV0a5EsHtEvBPYHzhG0vtqF4iISRExJiLGdHR0tD5CM7OKaEsiiIj56e9C4GpgbDviMDOzNiQCSetLGtY9DHwQmNXqOMzMLNOObw29EbhaUnf9l0XE/7QhDjMzow2JICIeA3Zudb1m9k8Tb3ykz2WP33f7AYzEVgX++qiZWcU5EZiZVZwTgZlZxTkRmJlVXDv7GjIb9Ppz03Wwauc2+0Z1OdwiMDOrOCcCM7OKcyIwM6s4JwIzs4rzzWKzQaqKN6oHo/6+T624Qe4WgZlZxTkRmJlVnBOBmVnFORGYmVWcbxab2aDhG+TlcIvAzKzi2pIIJO0n6c+S5ko6qR0xmJlZph3PLB4C/AjYH9gROEzSjq2Ow8zMMu1oEYwF5kbEYxHxKnA5cFAb4jAzM9pzs3hz4Onc+Dzg3bULSRoPjE+jSyX9uY/1jQCe62NZl3d5l3f5/pTv9zq+0r/yWxdZqB2JQHWmxesmREwCJvW7MqkzIsa4vMu7vMu3uvyqEkNv2nFpaB6wZW58C2B+G+IwMzPakwjuA7aTtI2ktYCPA9e2IQ4zM6MNl4YiYpmkY4E/AEOACyPioRKr7O/lJZd3eZd3+cEeQ48U8brL82ZmViH+ZbGZWcU5EZiZVdxqmwgkjZI0q91xVJ2k4yTNlvTzPpTdWNIXyoiriRiWtrn+O9tZvw0MSRMkndjuOBpZbRPB6kaZwfh+fQE4ICI+0YeyG6fylRUR7213DLb6G4wfLM0YIuk8SQ9JukHSukUL1rYoJJ0oaUIzlUv6iqRZ6fXlZsrmYpgt6cfA/az8+4si5X8jaVra/vG9l6hbd5/2X1rHucCbgWslHd9M2eQsYFtJ0yV9r9nCkg6XdG8q/9PUz1VLSDo735pJZ4Qn9GE9fWqRSNpV0kxJ60haP72Hb29yHZ9K65gh6ZImy54m6Uu58TMkHVew7ChJf5J0fvrf+bmkfSTdIWmOpLFNrGNy2oarJK1XsP6vdccqaaKkm9Pw3pIuLbKOtPw3U+eafwTeWrRcrvz6kn6X9v8sSYc2u47CImK1fAGjgGXA6DR+JXB4k+Vn5cZPBCY0Uf5dwIPA+sAGwEPALn3YhhXAbn3cB8PT33WBWcAmrdp/ufU8AYzox3s4q49ldwB+CwxN4z8GPtWH9SztY/27ALfmxh8GtmpV/ans6cB/kXXyeHKTZf8F+HP3e9d9LDX53t2fhtcAHi16/OWOvXekstOAC8l6JTgI+E3BdQSwexq/EDixYP27Ab9Mw7cB9wJDge8ARxVcR/f//3rAhsDcovXn1vG/gfNy4xv19Vjo7bW6twgej4jpaXga2cHRKv8KXB0RL0XEUuDXwB59WM+TEXF3H2M4TtIM4G6y1sR2TZZv5/7rr73J/hnvkzQ9jb+5VZVHxAPAppI2k7Qz8EJEPNWq+pNTgX2BMcB/Nll2L+CqiHgOICKeb6ZwRDwBLJK0C/BB4IGIWNTEKh6PiAcjYgXZSdRNkX0aPkjx4/DpiLgjDV9K9j9ZxDTgXZKGAa8Ad5Htwz3IEkMRe5D9/78cES/Stx/NPgjsk1qXe0TEX/uwjkJW9yeUvZIbXk52ZlzUMla+dLZOk3XX61OpL17qSyFJewL7AO+JiJclTaH5bejP/ms3AZMj4uQ2xnAVcAjwJrJedlttOFlrdCjZe9/MsSTq9AHWpPOBT5Nt/4VNls0feyty4yso/rlVG3+h7YmI1yQ9AXwGuBOYCXwA2BaYXbDuwvX1EMcjkt4FHACcKemGiDi1P+tsZHVvEfTHs2RndJtIWhs4sMnyU4GDJa0naX3gIxQ/mxgIG5Gdhb4s6W1kzd3BZgkwrI9lbwIOkbQpgKThkgr1xDiALifrQuUQsqTQapOAbwE/B85usuxNwMckbQLZ/utD/VcD+wG7kvUk0GpbSXpPGj4MuL2JslPJLgdPJfu/PRqYnlolRct/RNK6qWXx4SbqBkDSZsDLEXEp2SW+dza7jqJW9xZBn6WzglOBe4DHgT81Wf5+SReRXV8EOD9dLmiV/wGOljST7FpvXy8vtU1ELEo3CGcB10fEV5so+7CkU4Ab0retXgOOAZ4sKdx6MTyUPgSeiYgFraoXshu9wLKIuCzdJL9T0l4RcXOR8in2M4BbJS0HHiA7uy8sIl6VdAuwOCKWN7kJA2E2ME7ST4E5wE+aKHsb8E3groh4SdLfaeJELv3/XwFMJzvm+nIS+A7ge5JWkB2/n+/DOgpxFxNmVoqUgO8HPhoRc1pc9yjguoho6ptSVeVLQ2Y24JQ9fnYu2U3eliYBa55bBGZmFecWgZlZxTkRmJlVnBOBmVnFORFYW/TWh45qeh5Nfcf8xwDUK0k3S9pQPfRQm/q52bGfdW0mqaW/H5D0idS3zkxJd6ZfNXfP2y/1fTNX0km56ZdLavZX57YacSKwVVVtz6OjgKYSQYNO5g4AZqSf/TcUEUdGxMPN1FdnHfMj4pD+rKMPHgfeHxE7AaeRHnOY9sWPgP2BHYHDconuJ8DXWhynrUKcCKztJH1V0n3pLPa7aXJtz6NnAXuk8eMlDZH0vVy5o9K69pR0i6TLyPpqqfUJ4Jrc+Jr1eqiUNEXSmDS8VFnvmTMk3S3pjXW24f0ptumSHpA0LN/iSC2M7vldkr7Tw7b3WUTcGREvpNG7gS3S8FhgbkQ8FhGvkv3q+aA07zayPm38A9OKciKwtpL0QbLO8MYCo8k6+3ofcBLwaESMTr8oPgm4LY1PBI4A/hoRu5J1YfA5Sduk1Y4FvhkR9S7t7E7WqVi3twKT0hn0i9R//sH6wN0RsTNZ1wGfq7PMicAxETGarMOxv+VnphbGaLIP30XART1se+0+uiKXRPKvT9WJI+8I4Po0vDnwdG7evDSN1LHbXGBnrJJ8BmDt9sH06u5+YwOyD8feeur8ILCTpO5LLxulcq8C90bE4w3KDY+IJbnx2h4qjyPr1yXvVeC6NDyNrEfPWncA5yh7EtuvI2KetHK/g5LWAX4JHBsRT0r6IvW3fWq+XEQ03Q+9pA+QJYLuHjfrdYKY/xHRQmAzVk6SVhFOBNZuAs6MiJ+uNDHrIqC3cl+MiJU6M1PW62pPvWwuk7RGOguGYj1UvpbrbGw5df5vIuIsSb8juwdxt6R9gL/XLHYuWZL4Y24bXrfttVKfNfUebHJORFxcZ/mdyHr+3D/X9fM8Vn6w0RbA/Nz4OtS0Yqw6fGnI2u0PwGclbQAgaXNlPYbW9jxaO/4H4POShqZy2yvr5bU3f2bl5xL0p4fKf5C0beo//2ygE3hbzfxjgGERcVbNNtTb9pVExKHpkljtq14S2Irs2RefjIhHcrPuA7aTtI2ktch6Rc33kb89Wb//VkFuEVhbRcQNknYA7kqXUpaSPQntUeV6HgW+QXY2PwO4CPgh6SlYygp2AQcXqPJ3wJ5k18Shfz1U5n05XY5ZTvY0suuBkbn5JwKvKXtIDsC5EXFuvW0nu0zTV98GNgF+nNa5LCLGRMQySceSJZ8hwIUR8RBAuvn9t1b3kGqrDvc1ZJUiaSRwcUTUu85fScqeJ/1iRFzQ7lisPXxpyColnfWeJ2nDdseyClkMTG53ENY+bhGYmVWcWwRmZhXnRGBmVnFOBGZmFedEYGZWcU4EZmYV9/8BZP8qxD6cO9AAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "#import libraries\n",
    "from matplotlib import pyplot as plt\n",
    "\n",
    "#define file location\n",
    "filepath = 'C:/Users/rmartinez4/Box/DSE Masters/Fall 2019/day_1_python_and_unix/data/NLTK/'\n",
    "file_ = 'BrownNews.txt'\n",
    "\n",
    "#read file\n",
    "f = open(filepath+file_,'r')\n",
    "contents = f.read()\n",
    "\n",
    "#recycle code from above to get words as list\n",
    "# First, we replace the punctuations marks with spaces\n",
    "list_char = ['-','.',',','\\n',';','\"','``',\"''\"]\n",
    "for char in list_char:\n",
    "    contents = contents.replace(char,' ')\n",
    "#print Text\n",
    "print(contents)\n",
    "\n",
    "#convert text to list and remove spaces\n",
    "words_list = contents.split(' ')\n",
    "words_list = [i for i in words_list if i not in ('')]\n",
    "\n",
    "#get second letter from each word\n",
    "second_letter = []\n",
    "for word in words_list:\n",
    "    try:\n",
    "        second_letter = second_letter+[word[1]]\n",
    "    except IndexError:\n",
    "        print(word+' -> word with less than two letters')\n",
    "        \n",
    "#create distribution of letters as histogram\n",
    "plt.hist(second_letter, bins=20, alpha=0.5)\n",
    "plt.title('Distribution of second letter in each word')\n",
    "plt.xlabel('letter (bin size = 20)')\n",
    "plt.ylabel('count')\n",
    "\n",
    "plt.show()\n",
    "\n",
    "a=1; #if plt.show() is in the last line it won't show the plot"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(12) write a program to find solutions of the 8 queen problem.\n",
    ">The eight queens problem is the problem of placing eight queens on an 8×8 chessboard such that none of them attack one >another (no two are in the same row, column, or diagonal). Below is one of the arrangements of an 8 queen solution"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXEAAAD8CAYAAACB3pQWAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDIuMi4zLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvIxREBQAADgpJREFUeJzt3X+MZfVdxvHngZ1VfmPcBuksihttm6oJPyYQg8EqbYWUgBqNrT9aCfY2QdoS/1DUP8jGaGyM1SZGM1egaWOFWGojtg3SqNRWLeyCYPllLSMNOwh0o3ZLIc4O+/jH3E2G2bn33Jm95577Wd+vZLJnzr1nv09u9j575nvP+Y6TCABQ00ldBwAAbB8lDgCFUeIAUBglDgCFUeIAUBglDgCFUeIAUBglDgCFUeIAUNiOKYzBLaEAsHUe50nTKHEdPrg0jWG2bW7XHknSjp3zHScZbXVlWVKNnLOeUSLnpFXIWek9NC6mUwCgMEocAAqjxAGgMEocAAqjxAGgMEocAAqjxAGgMEocAAqjxAGgMEocAAprvO3e9hskXStpXmvroDwr6e4kT7ScDQDQYOSZuO1fk3Sn1hZieUDSvsH2HbZvbj8eAGCUpjPx6yV9X5LD63fa/qCkxyT97mYH2e5J6knS4uKirvvJN08gKgBgo6YSPyLptZK+umH/uYPHNpWkL6l/9NtZX8UQAKpqKvGbJP2t7X+X9Mxg33dK+h5JN7YZDADQbGSJJ7nH9uskXaK1DzYt6YCkfUlemUI+AMAIjVenJDki6YtTyAIA2CKuEweAwihxACiMEgeAwihxACiMEgeAwihxACiMEgeAwihxACjMSdoeo/UBAOAE5HGe1HjH5iTs2Dk/jWG2bXVlWRI5J2V1ZXnmM0prOSsszja3a0+Z13PWc1Z6D42L6RQAKIwSB4DCKHEAKIwSB4DCKHEAKIwSB4DCKHEAKIwSB4DCKHEAKIwSB4DCKHEAKGzbJW77ukkGAQBs3fGcie8d9oDtnu39tvf3+/3jGAIAMMrIVQxt/+uwhySdM+y4JH1JR9s7N9w4tO8BAMehaSnacyT9mKT/3rDfkv6plUQAgLE1lfinJJ2e5OGND9i+r5VEAICxjSzxJNePeOxnJx8HALAVXGIIAIVR4gBQGCUOAIVR4gBQGCUOAIVR4gBQGCUOAIVR4gBQmJO0PUbrAwDACcjjPKnptvuJ2LFzfhrDbNvqyrIkck7K6sryzGeUyDlpFXIefQ8dPrjUcZLR5nbtGfu5TKcAQGGUOAAURokDQGGUOAAURokDQGGUOAAURokDQGGUOAAURokDQGGUOAAU1ljitt9g+wrbp2/Yf2V7sQAA4xhZ4rbfJ+mvJL1X0qO2r1338O+0GQwA0KxpAax3S7o4yYu2z5d0l+3zk3xII1bYst2T1JOkxcXFCUUFAGzUVOInJ3lRkpI8bftNWivy79KIEk/Sl9Q/+u0NN+6dRFYAwAZNc+LP2b7g6DeDQr9a0i5JP9BmMABAs6YSf6ek59bvSLKa5J2SLm8tFQBgLCOnU5IcGPHYP04+DgBgK7hOHAAKo8QBoDBKHAAKo8QBoDBKHAAKo8QBoDBKHAAKo8QBoDAnaXuM1gcAgBPQ0PWp1uNMHAAKa1rFcDKD7JyfxjDbtrqyLImck7K6sjzzGaVaOQ8fXOo6RqO5XXtm/vWs9B4aF2fiAFAYJQ4AhVHiAFAYJQ4AhVHiAFAYJQ4AhVHiAFAYJQ4AhVHiAFBY4x2bti+RlCT7bL9R0pWSnkzymdbTAQBGGlnitm+RdJWkHbY/K+lSSfdJutn2hUl+u/2IAIBhms7Ef0rSBZK+RdJzknYnOWT79yTdL2nTErfdk9STpMXFxcmlBQC8StOc+GqSV5K8JOmpJIckKcnLko4MOyhJP8lCkoVerzfBuACA9ZpKfMX2qYPti4/utH2WRpQ4AGA6mqZTLk/yv5KUZH1pz0l6V2upAABjGVniRwt8k/0HJR1sJREAYGxcJw4AhVHiAFAYJQ4AhVHiAFAYJQ4AhVHiAFAYJQ4AhVHiAFCYk7Q9RusDAMAJyOM8iTNxACis8ZdCTGSQnfPTGGbbVleWJdXJefjgUsdJRpvbtWfmX0tp7fUk5+RUyFntvT4OzsQBoDBKHAAKo8QBoDBKHAAKo8QBoDBKHAAKo8QBoDBKHAAKo8QBoLAtl7jtj7YRBACwdSNvu7d998Zdkn7E9tmSlOSatoIBAJo1rZ2yW9Ljkm7V2mqElrQg6fdbzgUAGEPTdMqCpAcl/aakrye5T9LLST6X5HPDDrLds73f9v5+vz+5tACAVxl5Jp7kiKQ/sP3xwZ/PNx0zOK4v6Wh754Yb9x53UADAscZaijbJAUk/bfttkg61GwkAMK4trSee5NOSPt1SFgDAFnGdOAAURokDQGGUOAAURokDQGGUOAAURokDQGGUOAAURokDQGGUOAAU5iRtj9H6AABwAvI4T9rSbffbtWPn/DSG2bbVlWVJ5JyU1ZXlmc8okXPSVleWdfjgUtcxRprbtUdSjffQuJhOAYDCKHEAKIwSB4DCKHEAKIwSB4DCKHEAKIwSB4DCKHEAKIwSB4DCKHEAKGxLt93b/iFJl0h6NMm97UQCAIxr5Jm47QfWbb9b0h9JOkPSLbZvbjkbAKBB03TK3LrtnqS3JNkr6a2Sfm7YQbZ7tvfb3t/v9ycQEwCwmaYSP8n2t9n+dq0tW/s1SUryTUmrww5K0k+ykGSh1+tNMC4AYL2mOfGzJD2otXVtY/s7kjxn+3SNudYtAKA9I0s8yflDHjoi6ScmngYAsCXb+qUQSV6S9B8TzgIA2CKuEweAwihxACiMEgeAwihxACiMEgeAwihxACiMEgeAwihxACjMSdoeo/UBAOAENNbSJtu6Y3Orduycn8Yw27a6sixJOnxwqeMko83t2iOpxus56xklck5ahZxH3+tVco6D6RQAKIwSB4DCKHEAKIwSB4DCKHEAKIwSB4DCKHEAKIwSB4DCKHEAKIwSB4DCRpa47UttnznYPsX2Xtt/bfsDts+aTkQAwDBNZ+K3S3ppsP0hSWdJ+sBg34dbzAUAGEPTAlgnJVkdbC8kuWiw/QXbDw87yHZPUk+SFhcXjz8lAGBTTWfij9q+brD9iO0FSbL9OkmHhx2UpJ9kIclCr9ebUFQAwEZNJf5Lkn7Y9lOS3ijpn20vSfrTwWMAgA6NnE5J8nVJv2j7DEl7Bs8/kOT5aYQDAIw21i+FSPINSY+0nAUAsEVcJw4AhVHiAFAYJQ4AhVHiAFAYJQ4AhVHiAFAYJQ4AhVHiAFCYk7Q9RusDAMAJyOM8aaw7No/Xjp3z0xhm21ZXliWRc1JWV5Z1+OBS1zEaze3aM/OvpbT2epJzMiq9h8bFdAoAFEaJA0BhlDgAFEaJA0BhlDgAFEaJA0BhlDgAFEaJA0BhlDgAFEaJA0BhI0vc9vtsnzetMACArWk6E/8tSffb/rztG2y/ZhqhAADjaSrxJUm7tVbmF0t63PY9tt9l+4xhB9nu2d5ve3+/359gXADAek0lniRHktyb5HpJr5X0x5Ku1FrBDzuon2QhyUKv15tgXADAek1L0b5qPdskhyXdLelu26e0lgoAMJamM/GfGfZAkpcnnAUAsEUjSzzJl6cVBACwdVwnDgCFUeIAUBglDgCFUeIAUBglDgCFUeIAUBglDgCFUeIAUJiTtD1G6wMAwAnIzU+Zzpm4J/1l+z1t/L3knO0vcv7/ykjO8VSdTqmyNCI5J4uck1Mho0TORlVLHAAgShwASqta4lV+XRA5J4uck1Mho0TORtO4OgUA0JKqZ+IAABUscdtX2v4321+xfXPXeTZj+3bbL9h+tOssw9g+z/bf237C9mO23991ps3Y/lbbD9h+ZJBzb9eZRrF9su1/sf2prrMMY/tp21+y/bDt/V3nGcb22bbvsv3k4N/pD3adaSPbrx+8jke/Dtm+aaoZKk2n2D5Z0pclvUXSAUn7JL0jyeOdBtvA9uWSXpT00STf33Wezdg+V9K5SR6yfYakByX9+Ay+lpZ0WpIXbc9J+oKk9yf5YsfRNmX7VyQtSDozydVd59mM7aclLSQ52HWWUWx/RNLnk9xqe6ekU5P8T9e5hhn007KkS5N8dVrjVjsTv0TSV5IsJVmRdKekazvOdIwk/yDpv7rOMUqS/0zy0GD7G5KekDTfbapjZc2Lg2/nBl8zeeZhe7ekt0m6tess1dk+U9Llkm6TpCQrs1zgA1dIemqaBS7VK/F5Sc+s+/6AZrB4qrF9vqQLJd3fbZLNDaYoHpb0gqTPJpnJnJL+UNKvSjrSdZAGkXSv7Qdtz+rNNHskfU3ShwfTU7faPq3rUA3eLumOaQ9arcQ3uxV1Js/KqrB9uqRPSLopyaGu82wmyStJLpC0W9Iltmduisr21ZJeSPJg11nGcFmSiyRdJemXB9N/s2aHpIsk/UmSCyV9U9JMfgYmSYPpnmskfXzaY1cr8QOSzlv3/W5Jz3aUpbzBHPMnJH0syV92nafJ4Mfp+yRd2XGUzVwm6ZrBfPOdkn7U9p91G2lzSZ4d/PmCpE9qbZpy1hyQdGDdT113aa3UZ9VVkh5K8vy0B65W4vskfa/t7x78z/d2SXd3nKmkwQeGt0l6IskHu84zjO3X2D57sH2KpDdLerLbVMdK8utJdic5X2v/Lv8uyc93HOsYtk8bfJCtwfTEWyXN3FVUSZ6T9Izt1w92XSFppj503+Ad6mAqRVr7kaWMJKu2b5T0N5JOlnR7ksc6jnUM23dIepOkXbYPSLolyW3dpjrGZZJ+QdKXBvPNkvQbST7TYabNnCvpI4NP/k+S9BdJZvbyvQLOkfTJtf/DtUPSnye5p9tIQ71X0scGJ2xLkq7rOM+mbJ+qtSvm3tPJ+JUuMQQAvFq16RQAwDqUOAAURokDQGGUOAAURokDQGGUOAAURokDQGGUOAAU9n8xXKdaNytRfgAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "#import libraries\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "######################################## Functions ########################################\n",
    "\n",
    "#function to define an empty board\n",
    "def Get_board_grid(N):\n",
    "    board = np.zeros([N,N])\n",
    "    board[:] = np.nan\n",
    "    return board\n",
    "\n",
    "#check attack diagonally in all 4 directions\n",
    "def Check_Diagonal_attack(row,col,board,direction):\n",
    "    count = 0\n",
    "    while True:\n",
    "        try:   \n",
    "            #check if true or 1\n",
    "            if board[row,col] == 1:\n",
    "                count+=1\n",
    "            #check other diagonal locations based on direction\n",
    "            if direction == 'top-right':\n",
    "                row-=1\n",
    "                col+=1\n",
    "            elif direction == 'top-left':\n",
    "                row-=1\n",
    "                col-=1\n",
    "            elif direction == 'down-right':\n",
    "                row+=1\n",
    "                col+=1\n",
    "            elif direction == 'down-left':\n",
    "                row+=1\n",
    "                col-=1\n",
    "            #break prevent index from getting negative\n",
    "            if (row<0) or (col<0):\n",
    "                break\n",
    "        except IndexError:\n",
    "            break\n",
    "    #return number of attacks found\n",
    "    return count\n",
    "\n",
    "#check if the queen is under attack\n",
    "def Check_under_attack(row,col,board):\n",
    "    #check rows and cols\n",
    "    if sum(board[row,:] == True) > 1:\n",
    "        return True\n",
    "    elif sum(board[:,col] == True) > 1:\n",
    "        return True\n",
    "    #check diagonally \n",
    "    diagonal_counts = [Check_Diagonal_attack(row,col,board,'top-right'),Check_Diagonal_attack(row,col,board,'top-left'),\n",
    "                       Check_Diagonal_attack(row,col,board,'down-right'),Check_Diagonal_attack(row,col,board,'down-left')]\n",
    "    if sum(diagonal_counts) > 4:\n",
    "        return True\n",
    "    #return not in attack or false if the above is not true\n",
    "    else:\n",
    "        return False\n",
    "        \n",
    "######################################## Main ########################################\n",
    "    \n",
    "#define board \n",
    "N = 8\n",
    "Board = Get_board_grid(N)\n",
    "\n",
    "#define dictionary to store queens position\n",
    "dict_Q = {}\n",
    "for i in range(1,N+1):\n",
    "    dict_Q[i] = [i-1,np.nan]\n",
    "\n",
    "#initialize variables\n",
    "solutions = []\n",
    "Q = 1\n",
    "col = 0\n",
    "\n",
    "#loop to find all possible solutions\n",
    "while True:  \n",
    "    try:\n",
    "        #loop to find solution with backtracking strategy\n",
    "        while Q<len(dict_Q)+1:\n",
    "            try:\n",
    "                #find column where queen is not under attack\n",
    "                while True:\n",
    "                    #check each column by adding the queen to the board and updating the dictionary\n",
    "                    dict_Q[Q][1] = col #update dictionary\n",
    "                    Board[dict_Q[Q][0],dict_Q[Q][1]] = True #update board\n",
    "                    #if the queen is not under attack continue to the next queen\n",
    "                    if Check_under_attack(dict_Q[Q][0],dict_Q[Q][1],Board) == False:\n",
    "                        col = 0 #start with column 0 again\n",
    "                        Q+=1 #move to next queen\n",
    "                        break #Good, continue to next queen\n",
    "                    else:\n",
    "                        #if under attack, check next column, move out queen from board and reset dictionary information\n",
    "                        Board[dict_Q[Q][0],dict_Q[Q][1]] = np.nan #update board\n",
    "                        dict_Q[Q][1] = np.nan #update dictionary\n",
    "                        col+=1 #move to next column\n",
    "            except IndexError: #loop until we reach the end of the column\n",
    "                dict_Q[Q][1] = np.nan #reset current queen position\n",
    "                Q-=1 #BACKTRACKING\n",
    "                col = dict_Q[Q][1]+1 #move to next column\n",
    "                dict_Q[Q][1] = np.nan #reset previous queen position to find new solution\n",
    "                Board[Q-1,:] = np.nan #reset board from previous queen position\n",
    "                \n",
    "        #make a copy of the board for saving them on a list\n",
    "        copy_Board = np.copy(Board)\n",
    "        \n",
    "        #only save boards that are unique \n",
    "        if len(solutions) == 0:\n",
    "            solutions.append(copy_Board)\n",
    "        elif np.sum(np.equal(Board,solutions[0])) == N:\n",
    "            print('yes')\n",
    "        else:\n",
    "            solutions.append(copy_Board)\n",
    "            \n",
    "        #update previous board to start a new solution find\n",
    "        Q-=1 #BACKTRACKING\n",
    "        col = dict_Q[Q][1]+1 #move to next column\n",
    "        dict_Q[Q][1] = np.nan #update dictionary\n",
    "        Board[Q-1,:] = np.nan #update board\n",
    "    #continue until there is a key error to exit the loop\n",
    "    except KeyError:\n",
    "        break\n",
    "    \n",
    "#print one solution as an example in a heatmap\n",
    "example_board = np.copy(solutions[0])    \n",
    "example_board = np.nan_to_num(example_board)\n",
    "ax = sns.heatmap(example_board, linewidth=0.5, cbar = False)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<img src=\"8queen.jpg\">"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(13) Write a program to make a list of all prime numbers less than 3000. A prime number can only be divided evenly by 1 and itself."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163, 1171, 1181, 1187, 1193, 1201, 1213, 1217, 1223, 1229, 1231, 1237, 1249, 1259, 1277, 1279, 1283, 1289, 1291, 1297, 1301, 1303, 1307, 1319, 1321, 1327, 1361, 1367, 1373, 1381, 1399, 1409, 1423, 1427, 1429, 1433, 1439, 1447, 1451, 1453, 1459, 1471, 1481, 1483, 1487, 1489, 1493, 1499, 1511, 1523, 1531, 1543, 1549, 1553, 1559, 1567, 1571, 1579, 1583, 1597, 1601, 1607, 1609, 1613, 1619, 1621, 1627, 1637, 1657, 1663, 1667, 1669, 1693, 1697, 1699, 1709, 1721, 1723, 1733, 1741, 1747, 1753, 1759, 1777, 1783, 1787, 1789, 1801, 1811, 1823, 1831, 1847, 1861, 1867, 1871, 1873, 1877, 1879, 1889, 1901, 1907, 1913, 1931, 1933, 1949, 1951, 1973, 1979, 1987, 1993, 1997, 1999, 2003, 2011, 2017, 2027, 2029, 2039, 2053, 2063, 2069, 2081, 2083, 2087, 2089, 2099, 2111, 2113, 2129, 2131, 2137, 2141, 2143, 2153, 2161, 2179, 2203, 2207, 2213, 2221, 2237, 2239, 2243, 2251, 2267, 2269, 2273, 2281, 2287, 2293, 2297, 2309, 2311, 2333, 2339, 2341, 2347, 2351, 2357, 2371, 2377, 2381, 2383, 2389, 2393, 2399, 2411, 2417, 2423, 2437, 2441, 2447, 2459, 2467, 2473, 2477, 2503, 2521, 2531, 2539, 2543, 2549, 2551, 2557, 2579, 2591, 2593, 2609, 2617, 2621, 2633, 2647, 2657, 2659, 2663, 2671, 2677, 2683, 2687, 2689, 2693, 2699, 2707, 2711, 2713, 2719, 2729, 2731, 2741, 2749, 2753, 2767, 2777, 2789, 2791, 2797, 2801, 2803, 2819, 2833, 2837, 2843, 2851, 2857, 2861, 2879, 2887, 2897, 2903, 2909, 2917, 2927, 2939, 2953, 2957, 2963, 2969, 2971, 2999]\n"
     ]
    }
   ],
   "source": [
    "#define list to save prime numbers\n",
    "prime_num = []\n",
    "N_max = 3000\n",
    "\n",
    "#scan from 0 to 3000\n",
    "for number in range(0,N_max + 1):  \n",
    "   if number > 1: #1 is not prime, start after 1\n",
    "       for i in range(2,number): #verify is not divisible by other numbers\n",
    "           if (number % i) == 0:  \n",
    "               break #not prime\n",
    "       else:  #append prime numbers\n",
    "           prime_num.append(number)\n",
    "\n",
    "#print prime numbers\n",
    "print(prime_num)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(14) Solve the above problem using Set instead of List "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "set([2, 3, 5, 7, 11, 13, 2063, 17, 19, 2069, 23, 29, 31, 2081, 2083, 37, 2087, 41, 43, 47, 2099, 53, 59, 61, 2111, 2113, 67, 71, 73, 79, 2129, 83, 89, 2141, 2143, 97, 101, 2551, 103, 2153, 107, 109, 2749, 113, 127, 131, 137, 139, 149, 151, 2203, 157, 2207, 163, 2213, 167, 173, 179, 181, 2237, 191, 193, 2243, 197, 199, 2251, 211, 2267, 2053, 2269, 223, 2273, 227, 229, 233, 239, 241, 2293, 2089, 2297, 251, 257, 2309, 263, 269, 271, 277, 281, 283, 2333, 2437, 2339, 293, 2347, 2351, 307, 2357, 311, 313, 317, 2371, 2377, 331, 2381, 2383, 337, 2389, 2393, 347, 349, 2399, 353, 359, 2411, 2467, 367, 2417, 373, 2423, 379, 383, 389, 2441, 397, 2447, 401, 409, 2459, 419, 421, 2473, 2477, 431, 433, 439, 443, 449, 2503, 457, 461, 463, 467, 2521, 479, 2531, 487, 491, 2543, 2131, 2549, 503, 2731, 509, 521, 523, 2579, 2137, 541, 2591, 2593, 547, 557, 2609, 563, 569, 571, 2621, 577, 2633, 587, 593, 599, 601, 607, 2657, 2659, 613, 2663, 617, 619, 2671, 2677, 631, 2683, 2687, 641, 643, 2693, 647, 2699, 653, 499, 659, 661, 2711, 2713, 2719, 673, 677, 2161, 2729, 683, 691, 2741, 701, 2753, 709, 719, 727, 2777, 733, 739, 2789, 743, 2797, 751, 2801, 2803, 757, 2857, 761, 769, 2819, 773, 2833, 787, 2837, 2843, 797, 2851, 809, 811, 2861, 821, 823, 827, 829, 2879, 839, 2897, 853, 2903, 857, 859, 2909, 863, 2917, 877, 2927, 881, 883, 887, 2939, 2539, 2953, 907, 2957, 911, 2963, 919, 2969, 2281, 929, 937, 2887, 941, 947, 2999, 953, 967, 971, 977, 983, 991, 997, 2557, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 2239, 1151, 1153, 1163, 2221, 1171, 1181, 2767, 1187, 1193, 1201, 1213, 1217, 1223, 1229, 1231, 1237, 1249, 1259, 1277, 1279, 1283, 1289, 1291, 1297, 1301, 1303, 1307, 1319, 1321, 1327, 2341, 1361, 1367, 1373, 1381, 1399, 1409, 1423, 1427, 2707, 1429, 1433, 2287, 1439, 2971, 1447, 1451, 1453, 1459, 1471, 1481, 1483, 1487, 1489, 1493, 1499, 1511, 1523, 1531, 1543, 2647, 1549, 1553, 1559, 1567, 1571, 1579, 1583, 1597, 1601, 1607, 1609, 1613, 1619, 1621, 1627, 1637, 1657, 1663, 1667, 1669, 1693, 1697, 1699, 1709, 1721, 1723, 1733, 1741, 1747, 1753, 1759, 1777, 1783, 1787, 1789, 2689, 1801, 1811, 2617, 1823, 2311, 1831, 1847, 1861, 1867, 1871, 1873, 1877, 1879, 1889, 1901, 2791, 1907, 1913, 1931, 1933, 1949, 1951, 2179, 1973, 1979, 1987, 1993, 1997, 1999, 2003, 2011, 2017, 2027, 2029, 2039])\n"
     ]
    }
   ],
   "source": [
    "#define list to save prime numbers\n",
    "prime_num = set()\n",
    "N_max = 3000\n",
    "\n",
    "#scan from 0 to 3000\n",
    "for number in range(0,N_max + 1):  \n",
    "   if number > 1: #1 is not prime, start after 1\n",
    "       for i in range(2,number): #verify is not divisible by other numbers\n",
    "           if (number % i) == 0:  \n",
    "               break #not prime\n",
    "       else:  #append prime numbers\n",
    "           prime_num.add(number)\n",
    "           \n",
    "#print prime numbers\n",
    "print(prime_num)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
